import Head from "next/head";
import { useRouter } from "next/router";

export default function Os() {
  const router = useRouter();

  const os = router.query.os;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>You are using the {os} operating system</h1>
      </main>
    </div>
  );
}
